spring:
  application:
    name: streaming-app
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: kafka-streams-app
    properties:
      default:
        deserialization:
          exception:
            handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

